/*
LEEWAY HEADER — DO NOT REMOVE

REGION: DOCS.AGENT.GENERATOR
TAG: DOCS.STANDARD.DOCS.AGENT

COLOR_ONION_HEX:
NEON=#39FF14
FLUO=#0DFF94
PASTEL=#C7FFD8

ICON_ASCII:
family=lucide
glyph=book-open

5WH:
WHAT = Docs agent — generates structured plain-English docs from LEEWAY headers and registries
WHY = Human-readable documentation must be automatically derivable from code headers
WHO = Rapid Web Development
WHERE = src/agents/discovery/docs-agent.js
WHEN = 2026
HOW = Reads LEEWAY headers and produces Markdown documentation summaries

AGENTS:
DOCS
EXPLAIN
REGISTRY

LICENSE:
MIT
*/

import { readdir, readFile, writeFile, mkdir } from 'node:fs/promises';
import { join, relative, extname, dirname } from 'node:path';
import { parseHeader } from '../../core/header-parser.js';

const SKIP_DIRS = new Set(['.git', 'node_modules', 'dist', 'build', '.next', 'coverage', '.leeway']);
const CODE_EXTENSIONS = new Set(['.js', '.ts', '.jsx', '.tsx', '.mjs', '.cjs']);

/**
 * DocsAgent generates Markdown documentation from LEEWAY headers.
 */
export class DocsAgent {
  constructor(options = {}) {
    this.rootDir = options.rootDir || process.cwd();
    this.outputPath = options.outputPath || join(this.rootDir, 'docs', 'AUTO-GENERATED.md');
  }

  /**
   * Generate documentation for the entire codebase.
   * @returns {Promise<string>} - Markdown string
   */
  async generate() {
    const docs = [];
    docs.push('# LEEWAY Codebase Documentation\n');
    docs.push(`> Auto-generated by LEEWAY docs-agent on ${new Date().toISOString()}\n`);
    docs.push('---\n');

    const sections = new Map();
    await this._walk(this.rootDir, sections);

    for (const [region, files] of [...sections.entries()].sort()) {
      docs.push(`## ${region}\n`);
      for (const file of files) {
        docs.push(this._formatFileDoc(file));
      }
    }

    return docs.join('\n');
  }

  /**
   * Generate and save documentation to disk.
   * @returns {Promise<string>} - Path to saved file
   */
  async generateAndSave() {
    const content = await this.generate();
    await mkdir(dirname(this.outputPath), { recursive: true });
    await writeFile(this.outputPath, content, 'utf8');
    return this.outputPath;
  }

  async _walk(dir, sections, depth = 0) {
    if (depth > 8) return;
    let entries;
    try {
      entries = await readdir(dir, { withFileTypes: true });
    } catch {
      return;
    }

    for (const entry of entries) {
      if (SKIP_DIRS.has(entry.name)) continue;
      const fullPath = join(dir, entry.name);

      if (entry.isDirectory()) {
        await this._walk(fullPath, sections, depth + 1);
      } else if (CODE_EXTENSIONS.has(extname(entry.name))) {
        const relPath = relative(this.rootDir, fullPath);
        try {
          const content = await readFile(fullPath, 'utf8');
          const header = parseHeader(content);
          if (header) {
            const region = header.region?.split('.')?.[0] || 'UNKNOWN';
            if (!sections.has(region)) sections.set(region, []);
            sections.get(region).push({ path: relPath, header });
          }
        } catch {
          continue;
        }
      }
    }
  }

  _formatFileDoc({ path, header }) {
    const wh = header.fiveWH || {};
    return `### \`${path}\`
- **TAG**: \`${header.tag || 'N/A'}\`
- **WHAT**: ${wh.WHAT || 'N/A'}
- **WHY**: ${wh.WHY || 'N/A'}
- **HOW**: ${wh.HOW || 'N/A'}
- **Agents**: ${(header.agents || []).join(', ') || 'None declared'}

`;
  }
}
